---
title: "Improving the Model"
output:
html_document:
df_print: paged
author: "Krushang Shah & Rajiv Basnet"
date: "6/24/2020"
---

```{r setup, results='hide', message=FALSE}
library(tidyverse)
library(modelr)
library(plotly)
library(gtrendsR)
library(caret)
```

Let's check with author's data first.

```{r}
author_data <- read.csv("merged_author.csv")
author_data <- author_data %>% mutate(sales = log(sales), Period = as.Date(Period))
head(author_data)
```

Check and work with the data from 2004 to present:

```{r}
data <- read.csv("merged_present.csv")
data <- data %>% mutate(sales = log(sales), Period = as.Date(Period,"%m/%d/%Y"))
head(data)
```

```{r}

#using models defined in the paper to check how well it works with data from 2004 to present 
all_data <- data %>% 
  rename(actual = sales) %>%
  mutate(baseline = NA, trends = NA) %>%
  mutate(lag1 = lag(actual, 1), lag12 = lag(actual, 12))

K <- 17
num_rows <- nrow(all_data)
for (k in K: (num_rows -1) ) {
  model1 <- lm(actual ~ lag1 + lag12, data = all_data[1:k, ])
  model2 <- lm(actual ~ lag1 + lag12 + suvs + insurance, data = all_data[1:k, ])
  all_data$baseline[k + 1] <- predict(model1, all_data[k + 1,])
  all_data$trends[k + 1] <- predict(model2, all_data[k + 1,])
}

all_data[18:num_rows, ] %>% 
  pivot_longer(c("actual", "baseline", "trends"), names_to = "sales_type", values_to = "num_of_sales") %>%
  ggplot(aes(x = Period, y = num_of_sales, group = sales_type, color = sales_type)) +
  geom_line(aes(y = num_of_sales, color = sales_type, linetype= sales_type)) +
  scale_color_manual(values=c("black", "red", "darkgray")) +
  scale_linetype_manual(values=c("solid", "dashed", "solid")) +
  labs(x = "Date", y = "Log of Sales")
```


=> Would the models perform better if we were to use lags though (1:n months)?
Let's check it with author's data.

```{r results='hide', message=FALSE, warning= FALSE}
# checking model performances using data of (1 through 5) months before.

mae_baseline <-c()
mae_trends <- c()

all_data <- author_data %>% 
  rename(actual = sales) %>%
  mutate(baseline = NA, trends = NA) %>%
  mutate(lag12 = lag(actual, 12))

num_rows <- nrow(all_data)
num_lags <- 1:5

a <- c()

for (n in num_lags) {
  x <- rep(NA, num_rows)
  all_data <- cbind(all_data, x)
  m <- paste("lag", as.character(n), sep = "")
  names(all_data)[names(all_data) == "x"] <- m
  all_data <- all_data %>% 
    mutate(!!m := lag(actual, n))
  
  K <- 17
  
  outcome <- "actual"
  
  variables_mod1 <- all_data %>% select(-c(Period, baseline, trends, actual, suvs, insurance)) %>% names()
  
  variables_mod2 <- all_data %>% select(-c(Period, baseline, trends, actual)) %>% names()
  
  f1 <- as.formula(paste(outcome, paste(variables_mod1, collapse = " + "), sep = " ~ "))
  
  f2 <- as.formula(paste(outcome, paste(variables_mod2, collapse = " + "), sep = " ~ "))

  for (k in K: (num_rows - 1) ) {
    # get model1 : baseline
    model1 <- lm( formula = f1, data = all_data[1:k, ])

    #get  model2 : with trends
    model2 <- lm(formula = f2,  data = all_data[1:k, ])

    all_data$baseline[k + 1] <- predict(model1, all_data[k + 1,])
    all_data$trends[k + 1] <- predict(model2, all_data[k + 1,])
  }

  mae_baseline[n] <- sum(abs(all_data$actual - all_data$baseline), na.rm = TRUE)/(num_rows - K)
  mae_trends[n] <- sum(abs(all_data$actual - all_data$trends), na.rm = TRUE)/(num_rows - K)
}

```

```{r}
plot_mae <- data.frame(num_lags, mae_baseline, mae_trends) %>%
  pivot_longer(c(-num_lags), names_to = "mae_type", values_to = "mae")
ggplot(plot_mae, aes(x = num_lags, y = mae, color = mae_type)) +
  geom_line() +
  labs(x = "Number of Lags", y = "MAE")
```

